{% set python_min = '3.10' %}
{% set name = "django-dcat" %}
{% set version = "0.0.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django_dcat-{{ version }}.tar.gz
  sha256: bc26e2874a8f963061c492f908fd28c7264289ab3d948dea20ff73d3c65b641b

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - django >=5.0

test:
  imports:
    - dcat
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/pdelboca/django-dcat/
  summary: A Django app that provides a model layer and tools for DCAT applications.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
